# Generated by Django 3.0.8 on 2020-09-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='valor_compra',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor de Custo'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='valor_venda',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor de Venda'),
        ),
    ]
