# Generated by Django 3.0.8 on 2020-10-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_auto_20200921_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(max_length=25, unique=True, verbose_name='CPF ou CNPJ'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
